services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
      - 14269:14269
      - 14268:14268
    environment:
      COLLECTOR_OTLP_ENABLED: true
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - jaeger
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # default admin password (change as needed)
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    network_mode: host

volumes:
  grafana-storage:
