global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9191']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
