global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9191']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:9193' ]

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:9292' ]

  - job_name: 'jaeger'
    static_configs:
      - targets: ['localhost:14269']
